### ISSUE TITLE
LEARN section doesn't work

### ISSUE THREAD

**Issue by lbagella** [jsreport/website#7]
The "LEARN" section of the public website ( [https://jsreport.net/learn](https://jsreport.net/learn) ) doesn't work. It returns the following error:

{
  "error": "Failed to lookup view \"learn/docs/latest/pages/learn\" in views directory \"/app/views\""
}

**Comment by pofider** [comment]
Thank you for the heads up. It's fixed now.
I apologize for the inconvenience.

**Comment by lbagella** [comment]
don't worry. Many thanks !!!
L.


*Leonardo Bagella **Managing Director  -  *mobile: +39 351 956 7892


*AVVERTENZE PER LA PROTEZIONE DEI DATI PERSONALI*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceveste questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema; costituisce comportamento
contrario ai principi di protezione dei dati personali, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016, trattenere il messaggio
stesso, divulgarlo anche in parte, distribuirlo ad altri soggetti,
copiarlo, od utilizzarlo per finalità diverse.



*WARNINGS FOR THE PROTECTION OF PERSONAL DATA*

All information contained in this email message and/or in the attached
file/s is to be considered strictly confidential. Its use is allowed
exclusively by the recipient/s for the purposes indicated in the message.
If you received this email in error without being its recipient, please
notify the sender by email and delete it from your system. To retain this
message, disclose it even partially, distribute it, copy it, or use it for
any purpose constitutes behavior contrary to the principles of personal
data protection, pursuant to both art. 616 C.P. and GDPR 679/2016.
